#!/bin/bash
path=~/.radio
#path=~/programs/own/radio

get_url='select url from stations where name like "%'
get_url+="$1"
get_url+='%"'

get_names='select name from stations where name like "%'
get_names+="$1"
get_names+='%"'

get_random='select url from stations order by random() limit 1'
get_random_for_tag='select url from stations where tags like "%'
get_random_for_tag+="$2"
get_random_for_tag+='%" '
get_random_for_tag+='order by random() limit 1'

get_stations='select name from stations'

get_tag='select name from stations where tags like "%'
get_tag+="$2"
get_tag+='%"'

if [ -f ${path}/db.md5 ]; then
	echo "checking for new stations..."
	cd /tmp/
	wget https://raw.githubusercontent.com/todestoast/radio/master/db.md5
	if [ $(diff /tmp/db.md5 ${path}/db.md5 | wc -l) -gt 1 ]; then
		#different sum, download db
		echo "new stations found. downloading..."
		cd $path
		rm radio.db
		wget https://github.com/todestoast/radio/raw/master/radio.db
		echo "new stations added"
		rm /tmp/db.md5
	fi
else
	echo "Missing file. Downloading..."
	cd $path
	wget https://raw.githubusercontent.com/todestoast/radio/master/db.md5
fi

if [ -z "$1" ]; then
	echo "see --help for usage"
	exit 1
fi

case $1 in
	random)
		url=$(${path}/sqlite3 ${path}/radio.db "$get_random")
	;;
	-la|--list-all)
		stations=$(${path}/sqlite3 ${path}/radio.db "$get_stations")
		echo "$stations"
		exit 0
	;;
	-l|--list)
		if [ -z "$2" ]; then
			echo "Pass a word you want to search for"
			exit 1;
		else
			if [[ "$3" == "random" ]]; then
				url=$(${path}/sqlite3 ${path}/radio.db "$get_random_for_tag")
			else
				tags=$(${path}/sqlite3 ${path}/radio.db "$get_tag")
				echo "$tags"
				exit 0
			fi
		fi
	;;
	-h|--help)
		echo "usage: radio <stationname>"
		echo "example: radio kexp"
		echo ""
		echo "-h --help"
		echo "displays this help menu"
		echo
		echo "-l --list <search>"
		echo "search radiostations for specific word. This doesn't search for a stationname but for a tag."
		echo "example: radio -l ambient"
		echo "use 'radio <search> random' to randomly play a station that matches the search"
		echo "example: radio -l ambient random"
		echo
		echo "-la --list-all"
		echo "list all station Names (Caution: There might be a lot!)"
		exit 0
		;;
esac

if [ ${#url}  -eq 0 ]; then
 url=$(${path}/sqlite3 ${path}/radio.db "$get_url")
fi

#if no url was found
if [ ${#url}  -eq 0 ]; then
        echo "No station for $1 found :("
        exit 1
fi

#if string contains newlines therfore multiple urls
if [ $(echo "$url" | wc -l) -gt 1 ]; then
	#select names
	names=$(${path}/sqlite3 ${path}/radio.db "$get_names")
	echo "Multiple possible stations. Please specify!"
	echo "-------------------------------------------"
	echo "$names"
	exit 1;
else
	mplayer -quiet $url 2>&1
fi
exit 0
